### PR TITLE
updating README.md and creating basic ansible structure

### PR DESCRIPTION
**Pull request by sebinjohn**

### CODE REVIEW

**Comment by sujeshchirackkal** [comment]
Which version of vagrant is used in your machine? 'vagrant up' is giving me issue regarding the provider. I am using 1.7 (I am trying on master, not this PR yet)

**Comment by sebinjohn** [comment]
I am using Vagrant 1.8.1
What issues are you facing?

**Comment by Ranjandas** [comment]
Please upgrade to the latest vagrant and virtualbox version in your machines. We had found issues with older version not getting proper IP address and failing.
- Vagrant version - 1.8.1
- VirtualBox - 5.0.14

**Comment by sebinjohn** [comment]
@Ranjandas Do you want to update the README.md with this details?

**Comment by Ranjandas** [comment]
@sujeshchirackkal how about creating a `develop  branch and raise future pull requests against it. The merge to`master`will be from`develop` branch and will be only at the end of milestone (or once we prove the code is portable to a different kind of environment).

**Comment by Ranjandas** [comment]
@sebinjohn Please move all the ansible stuff into `ansible` directory.

**Comment by sebinjohn** [comment]
Okey. Done

**Comment by Ranjandas** [comment]
@sebinjohn let us move the inventory file to a separate directory.

**Comment by sebinjohn** [comment]
Moved inventory to a directory

**Pull request merged**
