### PR TITLE
Ensuring Docker Daemon is running

### PR DESCRIPTION
**Pull request by sebinjohn**
This PR contains 
- ensuring docker service is running
- updated README.md with more documentation

### CODE REVIEW

**Comment by Ranjandas** [comment]
Can you make sure the logo included doesn't have any copyright restrictions to use? If we are unsure, we will have to design a new one or go forward without one. It will be good to look for contents with Creative Commons licensing.

**Comment by sebinjohn** [comment]
Never thought about that.  Any idea? How it could be verified. Did some reverse image search. Couple of results came up, but they don't seem to be owned by anyone. But, yeah, lets remove it rather than running into issues.

**Comment by Ranjandas** [comment]
@sebinjohn can you update the PR by removing the logo so that we can merge it?

**Comment by sebinjohn** [comment]
Yes

**Comment by sebinjohn** [comment]
Removed logo

**Comment by sebinjohn** [comment]
Before merging we need to squash

**Pull request merged**
